#!/usr/bin/bash
set -e
# mount the special pseudo filesytems /proc and /sys
mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
cat /etc/hostname > /proc/sys/kernel/hostname
echo "Welcome to NoInit on $(cat /etc/issue)"
neofetch
read
